cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  image: ${docker_registry}redhawk/maven:3-jdk-8
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME !~ /^(\d+\.)?(\d+)?(\.\d+)$/ && $CI_PIPELINE_SOURCE !~ 'merge_request_event' && $CI_COMMIT_REF_NAME !~ /.*-external$/ && $CI_COMMIT_REF_NAME !~ master
  tags:
    - ide
  script:
    - mvn install sonar:sonar -P sign -P develop-2.2 -P with-metadata -D maven.test.failure.ignore=true
  artifacts:
    paths:
      - tests/*/target/surefire-reports/*.xml
    expire_in: 1 day

